### PR TITLE
Correct fake-factory package links to point to Faker

### PR DESCRIPTION
**Pull request by jeffwidman**
fake-factory moved to Faker on Pypi, with a minimum version of 0.7.3:
https://github.com/joke2k/faker/issues/331

### CODE REVIEW

**Comment by jeffwidman** [comment]
cc @fcurella - not sure if you have commit rights here

**Comment by fcurella** [comment]
@jeffwidman I dont have commit rights here, you'll have to get @joke2k involved

**Comment by jeffwidman** [comment]
ping @joke2k

**Comment by jeffwidman** [comment]
Bump @joke2k

**Comment by jeffwidman** [comment]
ping @joke2k

**Comment by jeffwidman** [comment]
Bump @joke2k

**Comment by jeffwidman** [comment]
nudge @joke2k

**Comment by jeffwidman** [comment]
nudge @joke2k

**Comment by jeffwidman** [comment]
@joke2k can you take a look at this one too? Also fixing a URL...

**Comment by joke2k** [comment]
> @joke2k can you take a look at this one too? Also fixing a URL...

I suppose that is passed enough time XD

**Comment by jeffwidman** [comment]
This does win the prize for the longest a PR of mine sat open before being merged. 😀

**Pull request merged**
